openapi: 3.0.3
info:
  title: Email & Journey Orchestration API
  version: 1.0.0
  description: Personalization strategies for cruise guests through email and journey flows.
paths:
  /personalization/email-journey:
    get:
      summary: Get email and journey orchestration settings
      responses:
        '200':
          description: Journey orchestration settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JourneyOrchestration'
components:
  schemas:
    JourneyOrchestration:
      type: object
      properties:
        tools:
          type: array
          items:
            type: string
        triggers:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              content:
                type: array
                items:
                  type: string
              conditions:
                type: array
                items:
                  type: string
              actions:
                type: array
                items:
                  type: string
              segments:
                type: array
                items:
                  type: string
              offers:
                type: array
                items:
                  type: string