openapi: 3.0.3
info:
  title: Cruise Port & Destination API
  version: 1.0.0
  description: API for retrieving destination information and port activities.
paths:
  /destinations:
    get:
      summary: List all available destinations
      responses:
        '200':
          description: A list of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "Santorini"
                    region:
                      type: string
                      example: "Mediterranean"
  /destinations/{portCode}/activities:
    get:
      summary: Get port activities by destination
      parameters:
        - in: path
          name: portCode
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Activities at port
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    activity:
                      type: string
                      example: "Wine tasting tour"
