openapi: 3.0.3
info:
  title: On-Site & App Personalization API
  version: 1.0.0
  description: Personalization techniques applied on-site and within mobile apps.
paths:
  /personalization/on-site-app:
    get:
      summary: Get on-site and app personalization settings
      responses:
        '200':
          description: App personalization settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppPersonalization'
components:
  schemas:
    AppPersonalization:
      type: object
      properties:
        tools:
          type: array
          items:
            type: string
        homepage_personalization:
          type: object
          properties:
            new_visitors:
              type: string
            returning_guests:
              type: string
        onboard_app:
          type: object
          properties:
            features:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  personalized_by:
                    type: array
                    items:
                      type: string
                  examples:
                    type: array
                    items:
                      type: string