openapi: 3.0.3
info:
  title: Loyalty Rewards Personalization Schema
  version: 1.0.0
  description: >
    This schema defines the structure of loyalty rewards used in cruise
    personalization strategies. It outlines platforms, tier-based benefits,
    and automated triggers for earning or redeeming loyalty points.
  contact:
    name: PingQuack Inc.
    email: support@pingquack.com
    url: https://www.pingquack.com

servers:
  - url: https://api.sailsync.com/v1
    description: Production server

paths:
  /example:
    get:
      summary: Example placeholder endpoint
      responses:
        '200':
          description: Successful response

components:
  schemas:
    LoyaltyRewards:
      type: object
      description: Tools and structures used to implement and manage guest loyalty reward programs.
      properties:
        reward_triggers:
          type: array
          description: Events that generate loyalty points or rewards automatically.
          items:
            $ref: '#/components/schemas/RewardTrigger'
        tiers:
          type: array
          description: Reward levels assigned to guests based on activity or spend.
          items:
            $ref: '#/components/schemas/LoyaltyTier'
        tools:
          type: array
          description: Platforms used for tracking loyalty tiers, points, and guest engagement.
          items:
            type: string
            enum:
              - Salesforce Loyalty Management
              - Oracle Loyalty Cloud
              - Annex Cloud

    LoyaltyTier:
      type: object
      required:
        - name
        - perks
      properties:
        name:
          type: string
          description: Name of the loyalty tier.
          example: Platinum
        perks:
          type: array
          description: Benefits associated with the tier.
          items:
            type: string
          example:
            - Priority boarding
            - Spa access
            - Free specialty dining

    RewardTrigger:
      type: object
      required:
        - event
        - points
      properties:
        event:
          type: string
          description: Behavior or milestone that activates a reward.
          example: Completed 5th cruise
        points:
          type: integer
          description: Number of loyalty points awarded.
          example: 500

x-personalization:
  loyalty_rewards:
    reward_triggers:
      - event: Completed 5th cruise
        points: 500
      - event: Referred a friend
        points: 300
      - event: Booked a suite
        points: 200
    tiers:
      - name: Gold
        perks:
          - Free welcome drink
          - 10% off onboard shopping
      - name: Platinum
        perks:
          - Priority boarding
          - Spa access
          - Free specialty dining
      - name: Diamond
        perks:
          - Personal concierge
          - Free shore excursions
          - Suite upgrade eligibility
    tools:
      - Salesforce Loyalty Management
      - Oracle Loyalty Cloud
      - Annex Cloud
