openapi: 3.0.3
info:
  title: Guest Check-In API
  version: 1.0.0
  description: API for handling facial recognition-based check-in and embarkation.

servers:
  - url: https://api.sailsync.com/v1
    description: Production server

paths:
  /checkin/facial-scan:
    post:
      summary: Submit facial scan for check-in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - imageData
              properties:
                imageData:
                  type: string
                  format: byte
                  description: Base64-encoded facial image data
      responses:
        '200':
          description: Guest matched and checked in
        '400':
          description: Invalid or missing image data

  /checkin/status/{guestId}:
    get:
      summary: Check-in status for a guest
      parameters:
        - in: path
          name: guestId
          required: true
          schema:
            type: string
          description: Unique identifier of the guest
      responses:
        '200':
          description: Current check-in status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [pending, confirmed, rejected]
                    description: Current status of guest check-in
        '404':
          description: Guest not found
