openapi: 3.0.3
info:
  title: Wallet API
  version: 1.1.0
  description: |
    A comprehensive API for managing onboard guest digital wallets, enabling balance retrieval, transactions, and historical ledger access.
    Integrates with guest profiles, booking services, ERP, and real-time notifications.

servers:
  - url: https://api.sailsync.com/v1
    description: Production

tags:
  - name: Wallet
    description: Guest digital wallet operations
  - name: Transactions
    description: Transaction history and audit

paths:
  /wallets/{guestId}/balance:
    get:
      tags: [Wallet]
      summary: Get wallet balance
      description: Retrieve the current wallet balance for the guest.
      parameters:
        - name: guestId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current wallet balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletBalance'
        '404':
          description: Guest wallet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /wallets/{guestId}/charge:
    post:
      tags: [Wallet]
      summary: Charge the guest wallet
      description: Deducts a specified amount from the wallet for a transaction, logs the event, and emits a webhook if configured.
      parameters:
        - name: guestId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChargeRequest'
            examples:
              spaCharge:
                summary: Spa Booking
                value:
                  amount: 79.99
                  reason: "Spa: Aromatherapy Massage"
                  metadata:
                    location: "Deck 5"
                    vendor: "Lotus Spa"
      responses:
        '201':
          description: Charge successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeResponse'
        '400':
          description: Invalid request or insufficient balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /wallets/{guestId}/transactions:
    get:
      tags: [Transactions]
      summary: List wallet transactions
      description: Returns paginated transaction history for the wallet.
      parameters:
        - name: guestId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionList'

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    WalletBalance:
      type: object
      properties:
        guestId:
          type: string
        balance:
          type: number
          format: float
        currency:
          type: string
          example: "USD"
        lastUpdated:
          type: string
          format: date-time

    ChargeRequest:
      type: object
      required: [amount, reason]
      properties:
        amount:
          type: number
          format: float
          minimum: 0.01
        reason:
          type: string
          maxLength: 100
        metadata:
          type: object
          additionalProperties:
            type: string
          description: Optional context info (e.g., vendor, location)

    ChargeResponse:
      type: object
      properties:
        transactionId:
          type: string
        newBalance:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time

    TransactionList:
      type: object
      properties:
        guestId:
          type: string
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    Transaction:
      type: object
      properties:
        transactionId:
          type: string
        timestamp:
          type: string
          format: date-time
        type:
          type: string
          enum: [charge, refund, adjustment]
        amount:
          type: number
          format: float
        reason:
          type: string
        metadata:
          type: object
          additionalProperties:
            type: string

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

security:
  - apiKeyAuth: []
